- hosts: webservers
  become: yes
  vars: #variables
    http_port: 8000
    https_port: 4443
    html_welcome_sg: "Hello World"
  tasks:
    - name: ensure apache is at the latest version
      apt:
        name: apache2
        state: latest